spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=OrderDB_1;characterEncoding=UTF-8;trustServerCertificate=true;
    username: sa
    password: 123456
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
      hibernate.enable_lazy_load_no_trans: true
  application:
    name: order-service
  kafka:
    producer:
      bootstrap-servers: localhost:29092
    consumer:
      bootstrap-servers: localhost:29092
server:
  port: 9007
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true