spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=UserDB_Test_10;characterEncoding=UTF-8;trustServerCertificate=true;
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898